-------------------------1번---------------------------------
-- 1번
-- 춘 기술대학교의 학과 이름과 계열을 조회하시오.
-- 단, 출력 헤더(컬럼명)는 "학과 명", "계열"으로 표시하도록 한다.
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-------------------------2번---------------------------------
-- 2번

SELECT  DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' "학과멸 정원"
FROM TB_DEPARTMENT;


-------------------------3번---------------------------------
SELECT DECODE(SUBSTR(STUDENT_SSN, 8,1),'2',STUDENT_NAME)
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN  = 'Y';



SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;


SELECT DEPARTMENT_NAME , CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY >= 20 AND CAPACITY <=30;

SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)= 2002 AND ABSENCE_YN = 'N';



--------------------------------------------------------------------------------------------

SELECT STUDENT_NO,STUDENT_NAME,  ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY EXTRACT(YEAR FROM ENTRANCE_DATE);

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

SELECT PROFESSOR_NAME 교수이름,
	FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19 || SUBSTR(PROFESSOR_SSN, 1, 6)))/12) 나이
FROM TB_PROFESSOR 
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY 나이 ASC ;

SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

SELECT
	CASE 
		WHEN LENGTH(PROFESSOR_NAME) = 3
		THEN SUBSTR(PROFESSOR_NAME , 2) 
		
		WHEN LENGTH(PROFESSOR_NAME) = 4
		THEN SUBSTR(PROFESSOR_NAME , 3)
	END 이름
FROM TB_PROFESSOR;

SELECT STUDENT_NO,STUDENT_NAME, EXTRACT(YEAR FROM ENTRANCE_DATE) - TO_NUMBER(19 || SUBSTR(STUDENT_SSN , 1,2))  AGE
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-TO_NUMBER(19 || SUBSTR(STUDENT_SSN , 1,2)) > 19;

SELECT STUDENT_NO, STUDENT_NAME
FROM  TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

SELECT FLOOR(AVG(POINT))
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

SELECT STUDENT_NAME
FROM TB_STUDENT 
ORDER BY SUBSTR(STUDENT_NAME, LENGTH(STUDENT_NAME)-1, LENGTH(STUDENT_NAME)) ;


-------------------------WORKBOOK3------------------------------------------------------
--1)
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY "학생 이름";

--2)
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC ;

--3)
-- 주소지가 강원도나 경기도인 학생들 중 1900년대 학번을 가진 학생들의
-- 이름과 학번, 주소를 이름 오름차순으로 조회하시오.
-- 단, 출력헤더에는 "학생이름", "학번", "거주지 주소"가 출력되도록 한다.
SELECT STUDENT_NAME, STUDENT_ADDRESS, ENTRANCE_DATE 
FROM TB_STUDENT
WHERE  SUBSTR(STUDENT_ADDRESS,1,3) = '경기도'
AND SUBSTR(ENTRANCE_DATE,1,2) = '19'

ORDER BY STUDENT_NAME;







