-------------------------1번---------------------------------
-- 1번
-- 춘 기술대학교의 학과 이름과 계열을 조회하시오.
-- 단, 출력 헤더(컬럼명)는 "학과 명", "계열"으로 표시하도록 한다.
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-------------------------2번---------------------------------
-- 2번

SELECT  DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' "학과멸 정원"
FROM TB_DEPARTMENT;


-------------------------3번---------------------------------
SELECT DECODE(SUBSTR(STUDENT_SSN, 8,1),'2',STUDENT_NAME)
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN  = 'Y';



SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;


SELECT DEPARTMENT_NAME , CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY >= 20 AND CAPACITY <=30;

SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)= 2002 AND ABSENCE_YN = 'N';



--------------------------------------------------------------------------------------------

SELECT STUDENT_NO,STUDENT_NAME,  ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY EXTRACT(YEAR FROM ENTRANCE_DATE);

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

SELECT PROFESSOR_NAME 교수이름,
	FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19 || SUBSTR(PROFESSOR_SSN, 1, 6)))/12) 나이
FROM TB_PROFESSOR 
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY 나이 ASC ;

SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

SELECT
	CASE 
		WHEN LENGTH(PROFESSOR_NAME) = 3
		THEN SUBSTR(PROFESSOR_NAME , 2) 
		
		WHEN LENGTH(PROFESSOR_NAME) = 4
		THEN SUBSTR(PROFESSOR_NAME , 3)
	END 이름
FROM TB_PROFESSOR;

SELECT STUDENT_NO,STUDENT_NAME, EXTRACT(YEAR FROM ENTRANCE_DATE) - TO_NUMBER(19 || SUBSTR(STUDENT_SSN , 1,2))  AGE
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-TO_NUMBER(19 || SUBSTR(STUDENT_SSN , 1,2)) > 19;

SELECT STUDENT_NO, STUDENT_NAME
FROM  TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

SELECT FLOOR(AVG(POINT))
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

SELECT STUDENT_NAME
FROM TB_STUDENT 
ORDER BY SUBSTR(STUDENT_NAME, LENGTH(STUDENT_NAME)-1, LENGTH(STUDENT_NAME)) ;


-------------------------WORKBOOK3------------------------------------------------------
--1)
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY "학생 이름";

--2)
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC ;

--3)
-- 주소지가 강원도나 경기도인 학생들 중 1900년대 학번을 가진 학생들의
-- 이름과 학번, 주소를 이름 오름차순으로 조회하시오.
-- 단, 출력헤더에는 "학생이름", "학번", "거주지 주소"가 출력되도록 한다.
SELECT STUDENT_NAME, STUDENT_ADDRESS, ENTRANCE_DATE 
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS,1,3) = '경기도'
AND SUBSTR(ENTRANCE_DATE,1,1) = '9';

-- 4번
-- 현재 법학과 교수의 이름, 주민등록 번호를 나이가 많은 순서부터 조회하시오.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
ORDER BY PROFESSOR_SSN;

--5번
-- 2004년 2학기에 'C3118100' 과목을 수강한 학생들의 학점을 조회하려고 한다.
-- 학점이 높은 학생부터 표시하고, 학점이 같으면 학번이 낮은 학생부터 조회하시오.
-- (참고) 소수점 아래 2자리까지 0으로 표현 : TO_CHAR(NUMBER, 'FM9.00')
-- (FM : 조회 결과 양쪽 공백 제거)
SELECT DISTINCT STUDENT_NO, TO_CHAR(POINT, 'FM9.00')학점
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
ORDER BY 학점 DESC;

-- 6번
-- 학생 번호, 학생 이름, 학과 이름을 학생 이름 오름차순으로 조회하시오.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;


-- 7번
-- 춘 기술대학교의 과목 이름, 해당 과목을 수업하는 학과 이름을 조회하시오.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- 8번
-- 과목, 해당 과목 교수 이름을 조회하시오.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_PROFESSOR USING (DEPARTMENT_NO);

-- 9번
-- 8번의 결과 중 '인문 사회' 계열에 속한
-- 과목명, 교수이름을 과목명 오름차순으로 조회하시오.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 10번
-- 음악학과 학생들의 "학번", "학생 이름", "전체 평점"을 조회하시오.
-- (단, 평점은 소수점 1자리까지만 반올림하여 표시한다.)
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름",TRUNC(POINT,2)
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능';


SELECT CATEGORY
FROM TB_DEPARTMENT;

--11번
--학번이 A313047인 학생의 학과이름, 학생이름, 지도교수 이름을 조회하시오.
SELECT DEPARTMENT_NAME,STUDENT_NAME,PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 12번
-- 2007년도에 '인간관계론' 과목을 수강한 학생을 찾아
-- 학생이름과 수강학기를 조회하는 SQL을 작성하시오.
SELECT DISTINCT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE SUBSTR(TERM_NO, 1,4) = '2007'
AND CLASS_NAME = '인간관계론'
ORDER BY TERM_NO;

-- 13번
-- 예체능 계열 과목 중 과목 담당교수를 한 명도 배정받지 못한 과목을 찾아
-- 과목 이름, 학과 이름을 조회하시오.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING DEPART














