-------------------------1번---------------------------------
-- 1번
-- 춘 기술대학교의 학과 이름과 계열을 조회하시오.
-- 단, 출력 헤더(컬럼명)는 "학과 명", "계열"으로 표시하도록 한다.
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-------------------------2번---------------------------------
-- 2번

SELECT  DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' "학과멸 정원"
FROM TB_DEPARTMENT;


-------------------------3번---------------------------------
SELECT DECODE(SUBSTR(STUDENT_SSN, 8,1),'2',STUDENT_NAME)
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN  = 'Y';



SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

SELECT DEPARTMENT_NAME , CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY >= 20 AND CAPACITY <=30;

SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;

SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)= 2002 AND ABSENCE_YN = 'N';



--------------------------------------------------------------------------------------------

SELECT STUDENT_NO,STUDENT_NAME,  ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY EXTRACT(YEAR FROM ENTRANCE_DATE);

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

SELECT PROFESSOR_NAME,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD')
FROM TB_PROFESSOR;

SELECT SUBSTR(PROFESSOR_NAME,2)
FROM TB_PROFESSOR;

SELECT STUDENT_NO,STUDENT_NAME, EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN , 1,6)))  AGE
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN , 1,6))) > 19;

SELECT STUDENT_NO, STUDENT_NAME
FROM  TB_STUDENT
WHERE SUBSTR(STUDENT_NO , 1,1) <> 'A';

SELECT FLOOR(AVG(POINT))
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';




